# Generated by Django 4.2.13 on 2024-05-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="uFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("accno", models.CharField(max_length=50)),
                ("custState", models.CharField(max_length=50)),
                ("custPin", models.PositiveBigIntegerField()),
                ("dpd", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
